development:
  adapter: postgresql
  encoding: unicode
  database: infonav_development
  host: localhost
  pool: 5
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: infonav_test
  host: localhost
  pool: 5
  username: postgres
  password: root
